### ISSUE TITLE
Problem after ubuntu update

### ISSUE THREAD

**Issue by whande1992** [devqore/myrdp#16]
Problem after ubuntu update

PRETTY_NAME="Ubuntu 19.10"

This is FreeRDP version 2.1.1 (n/a)

/home/wanderlei/Downloads/App/myrdp-2018-2-0/libz.so.1: version ZLIB_1.2.9 not found (required by /usr/local/lib/libpng16.so.16)

![image](https://user-images.githubusercontent.com/19689311/84179893-04f3fa00-aa5d-11ea-9070-bdf655dcff96.png)

![image](https://user-images.githubusercontent.com/19689311/84179934-14734300-aa5d-11ea-8385-c749627dea9f.png)

**Comment by devqore** [comment]
@whande1992 thanks for the report, I'll check this later.

**Comment by devqore** [comment]
@whande1992 could you check this pre-release binary https://github.com/devqore/myrdp/releases/download/2018.2.1/myrdp-2018.2.1.tar.bz2 ?

**Comment by whande1992** [comment]
> @ whande1992 você poderia verificar este binário de pré-lançamento https://github.com/devqore/myrdp/releases/download/2018.2.1/myrdp-2018.2.1.tar.bz2 ?

Unfortunately the same problem occurs.
`2020-06-18 09:15:39,660][DEBUG] b"xfreerdp: /home/wanderlei/Downloads/App/myrdp-2018.2.1/libz.so.1: version `ZLIB_1.2.9' not found (required by /usr/local/lib/libpng16.so.16)\n"`

**Comment by devqore** [comment]
@whande1992  thanks for checking, I'll try to investigate the problem this week.

**Comment by devqore** [comment]
I reproduced issue on Ubuntu 19.10 and applied a fix. New binary is available as prerelease https://github.com/devqore/myrdp/releases/download/2018.2.1/myrdp-2018.2.1.tar.bz2.

@whande1992 once again, thanks for the report.
