### ISSUE TITLE
please add duplicate function

### ISSUE THREAD

**Issue by mac-linux-free** [devqore/myrdp#7]
would be nice to have right mouseclick duplicate entry..many thx

**Comment by mac-linux-free** [comment]
Yes I´m using pacmanager for now but it is buggy at least for xfreerdp-connections on my arch plasma desktop. So I need to copy a connection with host, user and password and after that edit just the IP. thx

**Comment by devqore** [comment]
Ok, now I get it. I will try to look on this.

**Comment by devqore** [comment]
Maybe better solution will be something like was proposed in issue #8 in point 4? This means adding ability to set a default username and password for the group. I think that should also cover your case.

**Comment by mac-linux-free** [comment]
yes this could be a solution...but I have 100rdp connections so I need to be able to duplicate, too.

**Comment by mac-linux-free** [comment]
thank you very much
