### ISSUE TITLE
thanks and some feature request

### ISSUE THREAD

**Issue by dv8472** [devqore/myrdp#8]
Great app! Thank you!!!
Finally someone moved the server's list to the left or right, to imitate the MS's "Remote Desktop Connection Manager" behaviour a little.

If I might have few feature suggestions:
1.  an option setting for "Alt + F4" behaviour, whether these keys should close whole app or will just minimize it to the tray. And perhaps moving app. closure to "Ctrl + Q"?
2.  an option whether the session window in top should be closed after logoff or not. For now it just leaves the xfreerdp's output with "Process has been stopped..", but auto-closure after logoff would be fine too.
3.  an option whether the opened session tabs should be listed on the top, or to behave a little closer like MS's "Remote Desktop Connection Manager": by selecting a server (keeping it highlighted) in the list and opening it's session - either already existing/connected one or to start new one if disconnected.
4.  like in MS's "Remote Desktop Connection Manager", to add/edit login credentials for a group, where group's hosts could select option whether to inherit these from parent group or to use own - per host credentials (like it's now). This would make the administration of a large host numbers much easier, in case they use the same login credentials.
5.  expand/collapse (+/-) group's content.
None of these are life important, but would be great to have.

Thanks in advance for any of these features in case you decide to go for it.

**Comment by devqore** [comment]
I think that some of this features could be done, but I don't know exactly when and which one will be first :)

**Comment by devqore** [comment]
I made only one point from the list (4.), but I'm closing whole issue, because at this time I don't have to much time to implement other points and also in my opinion, should be only one feature request in issue.
