### ISSUE TITLE
Awesome app, one small request

### ISSUE THREAD

**Issue by khallZD** [devqore/myrdp#9]
Just wanted to say your this app is AWESOME!! After Remmina crashed on me one too many times I looked around for a replacement, and found MyRDP. Very impressed.

Just wanted to throw one suggestion at you that I miss about Remmina...the ability to change passwords in bulk. Something simple like if user = "xxxxxx" change password to "yyyyyy". It's not a huge deal breaker, but for someone who has to admin 500+ MS IIS servers on several domains it would be very helpful.

Keep up the great work.

**Comment by devqore** [comment]
Hey, I started work on the one of the features requested in #8, to add ability to set default username and password for the group, maybe this also solves your problem? But I'm not sure when this will be finished because right now I don't have to much time.

**Comment by khallZD** [comment]
That would be awesome, since I group my connections by domain. Like I said, you're app is great and I understand not having much time. Not a huge deal breaker at all.

**Comment by devqore** [comment]
I added ability to set default username and password for groups (2b52acef2322bb6d5b9e336e7a03cec206cc95d7), so I think this issue could be closed.
